### ISSUE TITLE
Add ChangeLog

### ISSUE THREAD

**Issue by zll600** [Talljack/react-starter#1]
Could you consider adding a `changlog`?
FYI:
- https://keepachangelog.com/en/1.1.0/

**Comment by Talljack** [comment]
yep, will use https://github.com/conventional-changelog/conventional-changelog to generate changelog

**Comment by Talljack** [comment]
Yep, but I think generating changelog by git metadata may be incorrect, what do you think? @zll600

**Comment by zll600** [comment]
> Yep, but I think generating changelog by git metadata may be incorrect, what do you think? @zll600

IMO, I prefer to write the changlog myself instead of using git commit to generate. But I am a front-end newbie, maybe your solution is better.

**Comment by Talljack** [comment]
> > Yep, but I think generating changelog by git metadata may be incorrect, what do you think? @zll600
> 
> IMO, I prefer to write the changlog myself instead of using git commit to generate. But I am a front-end newbie, maybe your solution is better.

I think writing by the owner is better.
